Assessments/Actual/rails_2_production_A/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index]
  resources :poems, only: [:new, :create, :update, :edit, :index]
  resource :session, only: [:new, :create, :destroy]
end

Assessments/Actual/rails_2_production_A/app/models/poem.rb
# == Schema Information
#
# Table name: poems
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  stanzas    :string           not null
#  complete   :boolean          not null
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Poem < ApplicationRecord
    validates :title, :stanzas, presence: true
    validates :complete, inclusion: [true, false]
    
    attr_accessor :author_id

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User
end

Assessments/Actual/rails_2_production_A/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    # SPIRE
    validates :username, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}

    attr_reader :password
    
    after_initialize :ensure_session_token

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.base64(64)
        self.save
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.base64(64)
    end

    has_many :poems,
        foreign_key: :author_id,
        class_name: :Poem
end 

Assessments/Actual/rails_2_production_A/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # CRRLLL
    helper_method :logged_in?, :current_user

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def login(user)
        # @current_user = user
        session[:session_token] = user.reset_session_token!
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def logout
        @current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end

    def logged_in?
        !!current_user
    end

end

Assessments/Actual/rails_2_production_A/app/controllers/poems_controller.rb
class PoemsController < ApplicationController
    
    before_action :require_logged_in
    
    def new
        @poem = Poem.new
        render :new
    end

    def index
        @poems = Poem.all
        render :index
    end

    def create
        @poem = Poem.new(poem_params)
        @poem.author_id = params[:author_id]
        if @poem.save
            redirect_to poems_url(@poem)
        else
            flash[:errors] = ["Stanzas can't be blank"]
            render :new
        end
    end

    def edit
        @poem = current_user.poems.find_by(id: params[:id])
        render :edit
    end

    def update
        @poem = current_user.poems.find_by(id: params[:id])
        if @poem
            @poem.update!(poem_params)
            redirect_to poems_url
        else
            flash[:errors] = ["Something went wrong!"]
        end
    end

    def poem_params
        params.require(:poem).permit(:title, :stanzas, :complete, :author_id)
    end
end

Assessments/Actual/rails_2_production_A/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, only:[:destroy]
    
    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if @user
            login(@user)
            redirect_to poems_url
        else
            flash[:errors] = ["Invalid username or password"]
            render :new
        end
    end

    def destroy
        logout if logged_in?
        redirect_to new_session_url
    end
end

Assessments/Actual/rails_2_production_A/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            login(@user)
            redirect_to poems_url           
        else
            flash[:errors] = @user.errors.full_messages
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

Assessments/Actual/rails_2_production_A/app/helpers/poems_helper.rb
module PoemsHelper
end

Assessments/Actual/rails_2_production_A/app/views/poems/edit.html.erb
<h1>Edit Poem</h1>
<form action = "<%=edit_poem_url(@poem)%>" method = "GET">
<label>Title
    <input name = "poem[title]" value = "<%= @poem.title %>">
</label>
<label>Stanzas
    <input name = "poem[stanzas]" value = "<%= @poem.stanzas %>">
</label>
<button>Edit Poem</button>
</form>

Assessments/Actual/rails_2_production_A/app/views/poems/index.html.erb
<h1>All Poems</h1>
<form action = "<%= poems_url %>" value = "POST">
<%= @poems.each do |poem| %>
    <p><%= poem.title %></p>
    <p><%= poem.stanzas %></p>
    <% if poem.complete %>
    <p>Done</p>
    <% end %>
    <a href="<%=edit_poem_url(poem) %>">Edit Poem</a>
<% end %>
</form>
<a href="<%=new_poem_url%>">Create New Poem</a>

Assessments/Actual/rails_2_production_A/app/views/poems/new.html.erb
<h1>Create New Poem</h1>
<form action = "<%= poems_url %>" method = "POST">
    <label>Title
        <input name = "poem[title]" value = "<%=@poem.title%>"/>
    </label>
    <label>Stanzas
        <input name = "poem[stanzas]" value = "<%=@poem.stanzas%>"/>
    </label>
    <label>Complete
        <label>true
            <input type = "radio" name = "poem[complete]" value = "true"/>
        </label>
        <label>false
            <input type = "radio" name = "poem[complete]" value = "false"/>
        </label>
    </label>
    <button>Create Poem</button>
</form>